name: venv
channels:
  - conda-forge
  - pytorch

dependencies:
  # core
  - python==3.7
  - pytorch==1.4.0
  # utils
  - torchvision==0.5.0
  - pillow>=5.2.0
  - matplotlib==3.1.1
  - pip:
    - pytorch-lightning==0.7.2
    - git+https://github.com/kornia/kornia
